In [1]:
import pandas as pd

In [2]:
ipl = pd.read_csv('matches.csv')

In [3]:
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05/04/17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06/04/17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07/04/17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08/04/17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08/04/17,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [4]:
ipl.tail()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
631,632,2016,Raipur,22/05/16,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,24/05/16,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,25/05/16,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,27/05/16,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,29/05/16,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [5]:
#importing from github 
ipl = pd.read_csv('https://raw.githubusercontent.com/training-ml/Files/main/matches.csv')
ipl.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,05/04/17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,06/04/17,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,07/04/17,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,08/04/17,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,08/04/17,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [6]:
ipl.shape

(636, 18)

In [7]:
ipl.sample(n=7)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
361,362,2012,Pune,11/05/12,Royal Challengers Bangalore,Pune Warriors,Pune Warriors,field,normal,0,Royal Challengers Bangalore,35,0,CH Gayle,Subrata Roy Sahara Stadium,BF Bowden,SK Tarapore,NaN
51,52,2017,Kanpur,13/05/17,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,8,Mohammed Siraj,Green Park,AK Chaudhary,Nitin Menon,NaN
233,234,2010,Mumbai,25/04/10,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Chennai Super Kings,22,0,SK Raina,Dr DY Patil Sports Academy,RE Koertzen,SJA Taufel,NaN
401,402,2013,Pune,17/04/13,Sunrisers Hyderabad,Pune Warriors,Pune Warriors,field,normal,0,Sunrisers Hyderabad,11,0,A Mishra,Subrata Roy Sahara Stadium,Asad Rauf,AK Chaudhary,NaN
322,323,2012,Delhi,19/04/12,Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,normal,0,Delhi Daredevils,0,5,KP Pietersen,Feroz Shah Kotla,BF Bowden,SK Tarapore,NaN
452,453,2013,Hyderabad,19/05/13,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata Knight Riders,bat,normal,0,Sunrisers Hyderabad,0,5,PA Patel,"Rajiv Gandhi International Stadium, Uppal",Asad Rauf,S Asnani,NaN
0,1,2017,Hyderabad,05/04/17,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [8]:
type(ipl)

pandas.core.frame.DataFrame

In [9]:
#Importing excel file
excel_file = pd.read_excel(r'C:\Users\shail\Desktop\Lead.xlsx',sheet_name='Sheet1')
excel_file

,Agreement Expiry Detail,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CustomerCode,CustomerName,SchoolId,SchoolName,GroupSchoolId,GroupSchoolName,SchoolAddress,TypeOfAgreement,Total No of Etec,DB_Type,...,Contact Person,Contact number,customer Debt,AreaManagerName,Regional Manager,RegionalManagerName,Divisonal Manager,DivisonalManagerName,SBH,SBH Name
2,TECE003586,Gurukul Vidyapeeth Khekra,ESCH010195,Gurukul Vidyapeeth Khekra,NaN,NaN,Pathshala Road Khekra,Fresh,42,SESPL,...,"Mr.Mukesh Gupta,Principal-Ms. Prabha",9643839730/Principal-9411695681,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
3,TECE000894,C.f Andrews School,ESCH017200,C.F Andrews School,NaN,NaN,balkeshwar road,Fresh,4,SESPL,...,muneesh agarwal,9720005923,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
4,TECE012878,Smart Business Incorporation,ESCH023322,Smart Business Incorporation,NaN,NaN,54 A civil Lines,Fresh,23,SESPL,...,Girdhar ji,9719316666,35700,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,TECE006023,Suditi Global Academy,ESCH019399,Suditi Global Academy,NaN,NaN,Near Ordinance Facto,Fresh,8,SESPL,...,NaN,NaN,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
61,TECE003494,Mihi Lal Baghel Public School,ESCH018344,Mihi Lal Baghel Public School,NaN,NaN,Dakhal,Fresh,3,SESPL,...,NaN,NaN,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
62,TECE002940,Rajiv International,ESCH008623,Rajiv International School Mathura,NaN,NaN,"NH-2, Mathura Delhi road",Fresh,17,SESPL,...,NaN,NaN,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
63,TECE005343,Shanti Niketan Public School,ESCH018900,Shanti Niketan Public School,NaN,NaN,Agra,Fresh,1,SESPL,...,NaN,NaN,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi
64,TEHW000870,M S School,ESCH018392,M S School,NaN,NaN,"NH-2, Agra-Firozabad road",Fresh,1,SESPL,...,NaN,NaN,NaN,Shailesh Kumar,ASG-0000026546,Amrit Anand,ASG-0000020676,Vacant DM UP Central -1,ASG-0000020618,Manish Kumar Dwivedi

In [10]:
#Exporting Data to current folder
ipl.to_csv('ipl_cleanup.csv')

In [11]:
#Exporting to different folder
ipl.to_csv(r'C:\Users\shail\Desktop\W\ipl_cleanup.csv',index=False, header=True)